title: "Syed Muhammad Zain"
author: "Syed Muhammad Zain"
description: "Personal site and writing space of Syed Muhammad Zain."
url: "https://zainarzg.github.io"
baseurl: ""
lang: "en"
timezone: "Asia/Karachi"
permalink: /insights/:title/
excerpt_separator: "\n\n\n"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      nav: blog
      body_class: page-post

exclude:
  - Gemfile
  - Gemfile.lock
  - templates

plugins:
  - jekyll-feed
